language: c++
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libldap2-dev
      - libkrb5-dev
      - libsasl2-dev
before_script: ./autogen.sh
script: ./configure && make
install: true
